import os

SECRET_FILE = os.getenv("ETESYNC_SECRET_FILE")
ALLOWED_HOSTS = os.getenv("ETESYNC_ALLOWED_HOSTS", "").split(",")
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = "DENY"
